### ISSUE TITLE
Obscure error when trying to build

### ISSUE THREAD

**Issue by clay53** [willir/cargo-ndk-android-gradle#7] opened 2020-12-14 20:00 UTC
This is my first time using this plugin so I'm not sure I have everything set up correctly but I followed the directions correctly afaik. Anyways, I'm getting this error:
```
Execution failed for task ':app:buildCargoNdkDebug'.
A problem occurred starting process 'command 'cargo''
```
`Cause: error=2, No such file or directory`
Idk what it means or how to fix it. I have cargo installed and it's runnable by a new terminal.

**Comment by clay53** [comment] 2020-12-14 21:22
Running with --debug
```
2020-12-14T16:15:55.106-0500 [INFO] [org.gradle.api.Task] Executing: [cargo, ndk, --target, aarch64-linux-android, --android-platform, 21, --, build, --verbose] from /home/clay53/git/github/clay53/cargondktest/android/app/src/main/rust with extra env: [:]
2020-12-14T16:15:55.106-0500 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'cargo''. Working directory: /home/clay53/git/github/clay53/cargondktest/android/app/src/main/rust Command: cargo ndk --target aarch64-linux-android --android-platform 21 -- build --verbose
2020-12-14T16:15:55.106-0500 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Environment for process 'command 'cargo'': {PATH=/app/bin:/usr/bin:, XAUTHORITY=/run/user/1000/Xauthority, INVOCATION_ID=479f6d520e794701bbf274a6085b800a, LC_MEASUREMENT=en_US.UTF-8, XMODIFIERS=@im=ibus, LC_TELEPHONE=en_US.UTF-8, MANDATORY_PATH=/usr/share/gconf/pop.mandatory.path, XDG_DATA_DIRS=/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share, GDMSESSION=pop, LC_TIME=en_US.UTF-8, PAPERSIZE=letter, DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus, DEFAULTS_PATH=/usr/share/gconf/pop.default.path, __INTELLIJ_COMMAND_HISTFILE__=/home/clay53/.var/app/com.google.AndroidStudio/config/Google/AndroidStudio4.1/terminal/history/history-3, XDG_CURRENT_DESKTOP=pop:GNOME, XDG_CACHE_HOME=/home/clay53/.var/app/com.google.AndroidStudio/cache, JOURNAL_STREAM=8:45782, SSH_AGENT_PID=2858, SESSION_MANAGER=local/clayton-pop-os:@/tmp/.ICE-unix/3121,unix/clayton-pop-os:/tmp/.ICE-unix/3121, USERNAME=clay53, LC_PAPER=en_US.UTF-8, ALSA_CONFIG_PATH=/usr/share/alsa/alsa-flatpak.conf, LOGNAME=clay53, GST_PLUGIN_SYSTEM_PATH=/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0, PWD=/home/clay53/git/github/clay53/cargondktest/android, MANAGERPID=2282, IM_CONFIG_PHASE=1, LANGUAGE=en_US:en, GJS_DEBUG_TOPICS=JS ERROR;JS LOG, SHELL=/bin/sh, LC_ADDRESS=en_US.UTF-8, GIO_LAUNCHED_DESKTOP_FILE=/home/clay53/.local/share/flatpak/exports/share/applications/com.google.AndroidStudio.desktop, AT_SPI_BUS_ADDRESS=unix:path=/run/user/1000/at-spi-bus, OLDPWD=/home/clay53/git/github/clay53/cargondktest/android, GNOME_DESKTOP_SESSION_ID=this-is-deprecated, GTK_MODULES=gail:atk-bridge:appmenu-gtk-module, _JAVA_OPTIONS=-Djava.io.tmpdir=/home/clay53/.var/app/com.google.AndroidStudio/cache, ALSA_CONFIG_DIR=/usr/share/alsa, XDG_SESSION_DESKTOP=pop, SHLVL=2, LC_IDENTIFICATION=en_US.UTF-8, LC_MONETARY=en_US.UTF-8, PULSE_CLIENTCONFIG=/run/user/1000/pulse/config, QT_IM_MODULE=ibus, JAVA_HOME=/app/extra/android-studio/jre, TERM=xterm-256color, XDG_CONFIG_DIRS=/app/etc/xdg:/etc/xdg, LANG=en_US.UTF-8, XDG_SESSION_TYPE=x11, FLATPAK_SANDBOX_DIR=/home/clay53/.var/app/com.google.AndroidStudio/sandbox, DISPLAY=:99.0, GI_TYPELIB_PATH=/app/lib/girepository-1.0, LC_NAME=en_US.UTF-8, XDG_SESSION_CLASS=user, FLATPAK_ID=com.google.AndroidStudio, XDG_DATA_HOME=/home/clay53/.var/app/com.google.AndroidStudio/data, DESKTOP_SESSION=pop, GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1, USER=clay53, XDG_MENU_PREFIX=gnome-, XDG_CONFIG_HOME=/home/clay53/.var/app/com.google.AndroidStudio/config, GIO_LAUNCHED_DESKTOP_FILE_PID=185694, QT_ACCESSIBILITY=1, WINDOWPATH=2, PULSE_SERVER=unix:/run/user/1000/pulse/native, TERMINAL_EMULATOR=JetBrains-JediTerm, GJS_DEBUG_OUTPUT=stderr, LC_NUMERIC=en_US.UTF-8, SSH_AUTH_SOCK=/run/user/1000/ssh-auth, GNOME_SHELL_SESSION_MODE=pop, XDG_RUNTIME_DIR=/run/user/1000, HOME=/home/clay53}
2020-12-14T16:15:55.106-0500 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
2020-12-14T16:15:55.106-0500 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'cargo'.
2020-12-14T16:15:55.111-0500 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
2020-12-14T16:15:55.111-0500 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'cargo'' finished with exit value -1 (state: FAILED)
```

**Comment by willir** [comment] 2020-12-23 00:31
Hi, thanks for reporting the issue.

Could you try running:

```sh
cargo ndk --target aarch64-linux-android --android-platform 21 -- build --verbose
```

from `/home/clay53/git/github/clay53/cargondktest/android/app/src/main/rust` and see whether it works manually?

**Comment by clay53** [comment] 2020-12-23 01:07
> Hi, thanks for reporting the issue.
> 
> Could you try running:
> 
> ```shell
> cargo ndk --target aarch64-linux-android --android-platform 21 -- build --verbose
> ```
> 
> from `/home/clay53/git/github/clay53/cargondktest/android/app/src/main/rust` and see whether it works manually?

It does.
```
cargo ndk --target aarch64-linux-android --android-platform 21 -- build --verbose
   Compiling lbrylite v0.1.0 (/home/clay53/git/github/clay53/lbrylite/rust)
     Running `rustc --crate-name lbrylite --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=4b5b4c20659a6a2c -C extra-filename=-4b5b4c20659a6a2c --out-dir /home/clay53/git/github/clay53/lbrylite/rust/target/aarch64-linux-android/debug/deps --target aarch64-linux-android -C linker=/home/clay53/Android/Sdk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -C incremental=/home/clay53/git/github/clay53/lbrylite/rust/target/aarch64-linux-android/debug/incremental -L dependency=/home/clay53/git/github/clay53/lbrylite/rust/target/aarch64-linux-android/debug/deps -L dependency=/home/clay53/git/github/clay53/lbrylite/rust/target/debug/deps`
    Finished dev [unoptimized + debuginfo] target(s) in 3.71s
```
Note: this is the same project with the same issue - it's just in a different directory now

**Comment by willir** [comment] 2020-12-23 01:12
Hmm.. Thanks for the quick reply. I will try to add more debugging to find out what the problem is.

**Comment by clay53** [comment] 2020-12-23 01:40
> Hmm.. Thanks for the quick reply. I will try to add more debugging to find out what the problem is.

Another note, [Mozilla's version](https://github.com/mozilla/rust-android-gradle) of this kind of plugin also doesn't work on my system.

**Comment by willir** [comment] 2020-12-27 02:42
Could you please try `0.3.1` version. I've added a few additional checks there. Maybe they would fire and it becomes clear what is wrong.

**Comment by clay53** [comment] 2020-12-27 04:08
Different error now

When running in Android Studio terminal:
```
sh-5.0$ ./gradlew assembleDebug
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/clay53/.var/app/com.google.AndroidStudio/cache
> Task :app:buildCargoNdkDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildCargoNdkDebug'.
> Cannot find 'cargo' executable in PATH: /app/bin:/usr/bin:

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 914ms
1 actionable task: 1 executed
```

My cargo is not located in those locations in the path so I know why that's an issue but it's the default install location for cargo afaik `$ whereis cargo -> cargo: /home/clay53/.cargo/bin/cargo` so that location should be in the PATH Android Studio (Android Studio path very different from normal PATH for some reason). I don't have to do anything special to get it working in a normal terminal.

Manually adding `/home/clay53/.cargo/bin` to path in Android Studio (though, I thought I tried this before):
```
sh-5.0$ ./gradlew assembleDebug
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/clay53/.var/app/com.google.AndroidStudio/cache

> Task :app:buildCargoNdkDebug FAILED
/home/clay53/.cargo/bin/cargo-ndk: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/clay53/.cargo/bin/cargo-ndk)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildCargoNdkDebug'.
> Process 'command 'cargo'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 914ms
1 actionable task: 1 executed
```
I'm not sure what to do with this. It still fails with the same error even after doing a full `source ~/.bashrc` to get a fully updated PATH.

Running in normal terminal: Succeeds now (didn't before with same old error)

**Comment by clay53** [comment] 2020-12-27 04:47
I tried uninstalling the Flatpak version of Android Studio and switching to the tar version 4.2 Beta 2 . It now builds fine from the Android Studio terminal but pressing the run button still fails with another obscure error.
```
Execution failed for task ':app:buildCargoNdkDebug'.
> Process 'command 'cargo'' finished with non-zero exit value 1
```

**Comment by willir** [comment] 2020-12-27 05:18
Wow, well, glibc errors are pretty nusty ones. Don't know enough about your system to tell what's is wrong.
When you compile project by pressing the run button the error message location might not be obvious, I guess it can be seen as a bug of the current project, I've just don't konw how best to solve it yet.

Anyway, you still can find full error output by selecting "build" tab at the buttom of Android Studio, and then selecting the top most error group (`Build: faild at`), it should show you the full log. Let me know if you need better instructions on how to find it.

**Comment by clay53** [comment] 2020-12-27 05:36
> Wow, well, glibc errors are pretty nasty ones. Don't know enough about your system to tell what's is wrong.
> 
> When you compile a project by pressing the run button the error message location might not be obvious, I guess it can be seen as a bug of the plugin, I've just don't know how best to solve it yet.
> 
> Anyway, you still can find full error output by selecting the "build" tab at the bottom of Android Studio, and then selecting the top most error group (`Build: failed at`), it should show you the full log. Let me know if you need better instructions on how to find it.

Ok, I see the full error now thanks.
```
Could not find any NDK.
Set the environment ANDROID_NDK_HOME to your NDK installation's root directory.

FAILURE: Build failed with an exception.
```

I have ANDROID_NDK_HOME defined in my ~/.bashrc already as `/home/clay53/Android/Sdk/ndk` which I'm fairly sure is what it's supposed to be.

**Comment by willir** [comment] 2020-12-27 14:08
If you launching Android Studio, not from the terminal (but like regular GUI application) - it won't include `~/.bashrc`, so if you have `ANDROID_NDK_HOME` only there it won't have it. `~/.bashrc` is only for interactive shells (and well Android Studio is not a bash anyway). You probably need to add it into `~/.profile`. Read about `~/.profile` vs `~/.bashrc`

I personally, usually, have separated file, like `~/.env_setup` where I keep all the stuff I need in the terminal and in GUI applications, like `JAVA_HOME`, `ANDROID_NDK_HOME`. And so I include that file (`source ~/.env_setup`) from both `~/.bashrc` and `~/profile`. Though your mileage may vary.

**Comment by clay53** [comment] 2020-12-28 07:28
I got it working now. I tried your suggestion with the `~/.profile` & `~/.env_setup` and it didn't work but at least now I know a little bit more about Linux. I should've just Googled a little harder for this one because the [second result](https://stackoverflow.com/questions/29122903/ndk-is-not-configured-issue-in-android-studio/29138361) told me what was wrong. I needed to add `ndk.dir=/home/clay53/Android/Sdk/ndk` to the `local.properties` file in my project (though, tbf to myself a bit - Android Studio is supposed to add that automatically and I checked - it was configured to do it). Anyway, it builds now. I think this issue can be closed then. Thanks a lot for your help!

**Comment by clay53** [comment] 2020-12-28 09:04
Ok, I'm going to be honest. I'm completely lost as to what I need to do next now that it's building. I tried going off of Mozilla's version of this and doing `System.loadLibrary("libname")` but it doesn't seem to be working.
```kotlin
package xyz.claytondoesthings.lbrylite

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log

class MainActivity : AppCompatActivity() {
    init {
        System.loadLibrary("lbrylite_sdk")
    }

    external fun getHi(): String

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        Log.d("HA", getHi())
    }
}
```
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xyz.claytondoesthings.lbrylite, PID: 16234
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xyz.claytondoesthings.lbrylite-lNVF_seDamsgBeKMpZQrsQ==/base.apk"],nativeLibraryDirectories=[/data/app/xyz.claytondoesthings.lbrylite-lNVF_seDamsgBeKMpZQrsQ==/lib/x86, /system/lib, /system/product/lib]]] couldn't find "liblbrylite_sdk.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at xyz.claytondoesthings.lbrylite.MainActivity.<init>(MainActivity.kt:9)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1243)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3182)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
I'm unsure of whether the rust library is being added to the apk at all because when I use APK Parser I don't see any .so files (though, I also am not sure if they'd show up using that app)

I also tried adding `librariesNames = ["liblbrylite_sdk.so"]` to `app/build.gradle` to no avail.
```
* What went wrong:
Execution failed for task ':app:buildCargoNdkDebug'.
> java.nio.file.NoSuchFileException: /home/clay53/git/github/clay53/lbrylite/android/../rust/target/aarch64-linux-android/debug/liblbrylite_sdk.so
```
Switching to other files that are there with a similar name but with a different extension (`.d`&`.rlib`) just produce the first error again during runtime.

**Comment by willir** [comment] 2020-12-29 16:17
About `~/.profile`, you usually need to restart your PC (or relogin) for effect to appear.

Anyway `ndk.dir` in `local.properties` is supported as well, I will soon update `README.md` to reflect it.

About `*.so` absence. What is your `crate-type`? It should be either `cdylib` or `dylib`. I think `cdylib` is recommended, though it might dramatically increase `*.so` file size.

Also, please use the lastest plugin version. In previous version it had a bug, and so it wouldn't automatically copy `cdylib` targets. See issue #8.

**Comment by clay53** [comment] 2020-12-30 01:15
Ok, that works now. I set it to cdylib for now. I still don't know how to export/import functions though. I think I'm importing correctly, I tried with both Java and Kotlin but I keep getting this error: `java.lang.UnsatisfiedLinkError: No implementation found for int com.claytondoesthings.lbrylite.MainActivity.get_hi() (tried Java_com_claytondoesthings_lbrylite_MainActivity_get_1hi and Java_com_claytondoesthings_lbrylite_MainActivity_get_1hi__)`. I haven't done this stuff before so I'd greatly appreciate your help.
Java code:
```java
package com.claytondoesthings.lbrylite;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity {

    static {
        System.loadLibrary("lbrylite_sdk");
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        TextView tv = (TextView) findViewById(R.id.sample_text);
        tv.setText(Integer.toString(get_hi()));
    }

    public native static int get_hi();
}
```
Kotlin code:
```kotlin
package xyz.claytondoesthings.lbrylite

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log

class MainActivity : AppCompatActivity() {
    init {
        System.loadLibrary("lbrylite_sdk")
    }

    external fun get_hi(): Int

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        Log.d("HA", get_hi().toString())
    }
}
```
I have this in Rust:
```rust
#[no_mangle]
pub extern "C" fn get_hi() -> i32 {
    53
}
```
I think that the function is in .so file but I don't know if it's exported incorrectly or something
```bash
clay53@clayton-pop-os:~/git/github/clay53/lbrylite/rust/target/x86_64-linux-android/debug$ nm -g liblbrylite_sdk.so  | grep " get_hi"
0000000000004760 T get_hi
```

**Comment by willir** [comment] 2020-12-30 03:04
I think the Rust function should be:

For your java code.

```rust
use jni::objects::JClass;
use jni::sys::jstring;
use jni::JNIEnv

#[no_mangle]
#[allow(non_snake_case)]
pub extern "C" fn Java_com_claytondoesthings_lbrylite_MainActivity_get_hi(env: JNIEnv, class: JClass) -> i32 {
    53
}
```

Or for Kotlin (it has a different package name):

```rust
use jni::objects::JClass;
use jni::sys::jstring;
use jni::JNIEnv

#[no_mangle]
#[allow(non_snake_case)]
pub extern "C" fn Java_xyz_claytondoesthings_lbrylite_MainActivity_get_hi(env: JNIEnv, class: JClass) -> i32 {
    53
}
```

You've said, you had tried `Java_com_claytondoesthings_lbrylite_MainActivity_get_1hi`. There seems to be an extra `1` before `hi` (at least it looks to me so). And I don't think it would work without those two parameters.

Alternatively, you can manually register your functions (export/import). [jni::register_native_methods](https://docs.rs/jni/0.18.0/jni/struct.JNIEnv.html#method.register_native_methods). However, it is usually more complicated and I would suggest making it work via automatic importing (with those ugly names `Java_...`).

I hope it helps.

**Comment by clay53** [comment] 2020-12-31 07:01
Everything works now! Thank you!!

**Comment by willir** [comment] 2020-12-31 19:50
Great. I'm glad it helped.
Closing issue.

**Closed by willir** 2020-12-31 19:50 UTC
